apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: nginx
    namespace: devcon
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: nginx
    type: ClusterIP
kind: List